---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2021-11-11 - 10:09:32 +0000
  labels:
    dev.okteto.com/auto-ingress: "true"
    app.kubernetes.io/name: papaya-mealmanager-be
  name: papaya-mealmanager-be
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: papaya-mealmanager-be
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2021-11-11 - 10:09:32 +0000
  labels:
    app.kubernetes.io/name: papaya-mealmanager-be
  name: papaya-mealmanager-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: papaya-mealmanager-be
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: 2021-11-11 - 10:09:32 +0000
      labels:
        app.kubernetes.io/name: papaya-mealmanager-be
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: l1n77/papaya-mealmanager-be
          imagePullPolicy: Always
          name: papaya-mealmanager-be
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
