---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: cb5749cdf31ebae01a305fd3474fca5148283206
    app.quarkus.io/build-timestamp: 2021-11-10 - 10:36:29 +0000
  labels:
    app.kubernetes.io/name: papaya-mealmanager-be
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: papaya-mealmanager-be
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: papaya-mealmanager-be
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: cb5749cdf31ebae01a305fd3474fca5148283206
    app.quarkus.io/build-timestamp: 2021-11-10 - 10:36:29 +0000
  labels:
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: papaya-mealmanager-be
  name: papaya-mealmanager-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
      app.kubernetes.io/name: papaya-mealmanager-be
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: cb5749cdf31ebae01a305fd3474fca5148283206
        app.quarkus.io/build-timestamp: 2021-11-10 - 10:36:29 +0000
      labels:
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/name: papaya-mealmanager-be
    spec:
      containers:
        - env:
            - name: Mealmanager
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: lintt/papaya-mealmanager-be:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          name: papaya-mealmanager-be
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
